/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.AlunoController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Aluno;

/**
 *
 * @author guto
 */
public class FormTelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form FormTelaInicial
     */
    public FormTelaInicial() {
        initComponents();
        PreencherTabela();
        telaGAluno.setVisible(false);
        btnAtualizar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGerenciarAlunos = new javax.swing.JButton();
        btnGerenciarLivros = new javax.swing.JButton();
        btnGerenciarEmprestimo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        telaGAluno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtEndereco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAtualizarAluno2 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/livros.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 153, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Biblioteca  Universitária");

        btnGerenciarAlunos.setBackground(new java.awt.Color(102, 255, 102));
        btnGerenciarAlunos.setForeground(new java.awt.Color(0, 0, 0));
        btnGerenciarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/alunos.png"))); // NOI18N
        btnGerenciarAlunos.setText("<html>\nGerenciar <br/> alunos\n</html>\n");
        btnGerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarAlunosActionPerformed(evt);
            }
        });

        btnGerenciarLivros.setBackground(new java.awt.Color(102, 255, 102));
        btnGerenciarLivros.setForeground(new java.awt.Color(0, 0, 0));
        btnGerenciarLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/livrosg.png"))); // NOI18N
        btnGerenciarLivros.setText("<html>\nGerenciar <br/>acervo\n</html>\n");
        btnGerenciarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarLivrosActionPerformed(evt);
            }
        });

        btnGerenciarEmprestimo.setBackground(new java.awt.Color(102, 255, 102));
        btnGerenciarEmprestimo.setForeground(new java.awt.Color(0, 0, 0));
        btnGerenciarEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/gerenciar.png"))); // NOI18N
        btnGerenciarEmprestimo.setText("<html>\nGerenciar <br/> empréstimos\n</html>\n\n");

        btnSair.setBackground(new java.awt.Color(102, 255, 102));
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_icons/sairg.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnGerenciarAlunos)
                    .addComponent(btnGerenciarLivros)
                    .addComponent(btnGerenciarEmprestimo)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(365, 365, 365)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(btnGerenciarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnGerenciarLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGerenciarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(0, 204, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Gerenciamento de alunos");

        lblMatricula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblMatricula.setText("n° matrícula:");

        lblNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNome.setText("nome:");

        lblCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCpf.setText("cpf:");

        lblCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCurso.setText("curso:");

        lblEndereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEndereco.setText("endereço:");

        lblTelefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTelefone.setText("telefone:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(0, 51, 255));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAtualizarAluno2.setBackground(new java.awt.Color(0, 153, 0));
        btnAtualizarAluno2.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarAluno2.setText("atualizar aluno");
        btnAtualizarAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarAluno2ActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(204, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizarAluno2)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizarAluno2)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        btnAtualizar.setBackground(new java.awt.Color(0, 153, 0));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "matrícula", "cpf", "nome", "curso", "endereço", "telefone"
            }
        ));
        jScrollPane1.setViewportView(tabelaAluno);

        javax.swing.GroupLayout telaGAlunoLayout = new javax.swing.GroupLayout(telaGAluno);
        telaGAluno.setLayout(telaGAlunoLayout);
        telaGAlunoLayout.setHorizontalGroup(
            telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaGAlunoLayout.createSequentialGroup()
                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(telaGAlunoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(telaGAlunoLayout.createSequentialGroup()
                                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMatricula)
                                    .addComponent(lblNome)
                                    .addComponent(lblCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(telaGAlunoLayout.createSequentialGroup()
                                        .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(telaGAlunoLayout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(lblCpf)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(telaGAlunoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblEndereco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(telaGAlunoLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lblTelefone)
                                                .addGap(7, 7, 7)
                                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(telaGAlunoLayout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAtualizar)
                                        .addGap(4, 4, 4)
                                        .addComponent(btnCancelar)))))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaGAlunoLayout.setVerticalGroup(
            telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaGAlunoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCurso)
                        .addComponent(lblTelefone)))
                .addGap(18, 18, 18)
                .addGroup(telaGAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnAtualizar))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaGAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaGAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnGerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarAlunosActionPerformed
        telaGAluno.setVisible(true);
    }//GEN-LAST:event_btnGerenciarAlunosActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    
    private boolean ConfereTextField(){
        if(txtMatricula.getText().isEmpty() || txtCpf.getText().isEmpty() || txtNome.getText().isEmpty() 
                || txtCurso.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtTelefone.getText().isEmpty()){
            return false;
        }
        return true;
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean verifica  = ConfereTextField();
        
        if(verifica){
            //model aluno
            Aluno a = new Aluno();

            a.setMatricula(Integer.parseInt(txtMatricula.getText()));
            a.setCpf(txtCpf.getText());
            a.setNome(txtNome.getText());
            a.setCurso(txtCurso.getText());
            a.setEndereco(txtEndereco.getText());
            a.setTelefone(txtTelefone.getText());

            //classe controller
            AlunoController ac = new AlunoController();
            ac.CadastrarAluno(a);
            PreencherTabela();
        }else{
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        boolean verifica  = ConfereTextField();
        
        if(verifica){
            Aluno a = new Aluno();
        
            a.setMatricula(Integer.parseInt(txtMatricula.getText()));
            a.setCpf(txtCpf.getText());
            a.setNome(txtNome.getText());
            a.setCurso(txtCurso.getText());
            a.setEndereco(txtEndereco.getText());
            a.setTelefone(txtTelefone.getText());

            AlunoController ac = new AlunoController();
            ac.AtualizarAluno(a);

            PreencherTabela();
            btnSalvar.setVisible(true);
            btnAtualizar.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
        }   
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int opcao = tabelaAluno.getSelectedRow();
        
        if(opcao >= 0){
            Aluno a = new Aluno();
            a.setMatricula(Integer.parseInt(tabelaAluno.getValueAt(opcao,0).toString()));
            a.setCpf(tabelaAluno.getValueAt(opcao,1).toString());
            a.setNome(tabelaAluno.getValueAt(opcao,2).toString());
            a.setCurso(tabelaAluno.getValueAt(opcao,3).toString());
            a.setEndereco(tabelaAluno.getValueAt(opcao,4).toString());
            a.setTelefone(tabelaAluno.getValueAt(opcao,5).toString());
            
            AlunoController ac = new AlunoController();
            
            ac.ExcluirAluno(a);
            PreencherTabela();
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione uma linha!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarAluno2ActionPerformed
        int opcao = tabelaAluno.getSelectedRow();
        if(opcao >=0){
            txtMatricula.setText(tabelaAluno.getValueAt(opcao,0).toString());
            txtCpf.setText( tabelaAluno.getValueAt(opcao,1).toString());
            txtNome.setText(tabelaAluno.getValueAt(opcao,2).toString());
            txtCurso.setText(tabelaAluno.getValueAt(opcao,3).toString());
            txtEndereco.setText(tabelaAluno.getValueAt(opcao,4).toString());
            txtTelefone.setText(tabelaAluno.getValueAt(opcao,5).toString());
            
            //deixar o botao atualizar visivel
            btnAtualizar.setVisible(true);
            btnSalvar.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Selecione uma linha!");
        }
    }//GEN-LAST:event_btnAtualizarAluno2ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtMatricula.setText("");
        txtCpf.setText("");
        txtNome.setText("");
        txtCurso.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        
        btnAtualizar.setVisible(false);
        btnSalvar.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGerenciarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarLivrosActionPerformed
        //abre o form de gerenciamento do acervo
        FormTelaGLivros formLivros = new FormTelaGLivros();
        formLivros.setVisible(true);
        //esconde o form que está aberto
        this.setVisible(false);
    }//GEN-LAST:event_btnGerenciarLivrosActionPerformed
    
    public void PreencherTabela(){
        AlunoController ac = new AlunoController();
        List<Aluno> lista = ac.ListarAlunos();
        
        DefaultTableModel  modeloTabela = (DefaultTableModel) tabelaAluno.getModel();
        modeloTabela.setRowCount(0);
        
        for(Aluno a : lista){
            modeloTabela.addRow(new Object[]{
                a.getMatricula(),
                a.getCpf(),
                a.getNome(),
                a.getCurso(),
                a.getEndereco(),
                a.getTelefone()
            });
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnAtualizarAluno2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGerenciarAlunos;
    private javax.swing.JButton btnGerenciarEmprestimo;
    private javax.swing.JButton btnGerenciarLivros;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JPanel telaGAluno;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
